### ISSUE TITLE
License

### ISSUE THREAD

**Issue by haneefmubarak** [majek/dump#1]
Hey, I wanted to use your spinlock code, but I noticed that there wasn't a license file or license included in the file.

Could you add a LICENSE file to the repo, preferably BSD, MIT, WTFPL, etc? Thanks!

**Comment by majek** [comment]
Consider the spinlock code MIT like this: https://github.com/majek/lua-channels/blob/master/LICENSE-MIT-lua-channels

**Comment by majek** [comment]
You mean this: https://github.com/majek/dump/blob/master/msqueue/pthread_spin_lock_shim.h

But your probably should ask someone smart if that is actually correct. writing locking routines correctly is very hard.

**Comment by haneefmubarak** [comment]
Have you seen: http://stackoverflow.com/questions/8177031/does-mac-os-x-have-pthread-spinlock-t-type

Anyways, I saw your post - I'll look into ConcurrencyKit if this doesn't end up working out. But thanks for clearing up the licensing anyways!

**Comment by diekmann** [comment]
Any license information about the other dumps?
I'm particularly interested in dump/vpn.

**Comment by majek** [comment]
The files "dump/vpn" are public domain. Feel free to do whatever you want  with them.

**Comment by diekmann** [comment]
thanks :+1: 
Added to our firewall dump collection (https://github.com/diekmann/net-network9
