### ISSUE TITLE
Use of SO_REUSEPORT may harm performance here

### ISSUE THREAD

**Issue by gz** [majek/dump#13]
https://github.com/majek/dump/blob/d8ea14a812d68acd8fc13dd06afba5aaf8bae785/how-to-receive-a-million-packets/net.c#L203

Just FYI you're hurting your performance numbers if you use SO_REUSEPORT on the sender side. An average NIC will include SRC Port and IP in the hash and this will ensure that all packets from a multi-threaded udpsender process get delivered to the same queue.

**Comment by majek** [comment]
The line you pointed to sets SO_REUSEADDR. This is not SO_REUSEPORT.

**Comment by gz** [comment]
Sorry, disregard what I wrote here, I remembered it incorrectly. The issue I saw a while back was that every thread uses the same source port to send packets (which then ended up all in a single receiver queue on the NIC of my server):
https://github.com/majek/dump/blob/d8ea14a812d68acd8fc13dd06afba5aaf8bae785/how-to-receive-a-million-packets/udpsender.c#L94

a simple +t to the port number should fix the issue.

**Comment by majek** [comment]
You are correct. The outbound traffic is routed to specific TX queue based on XPS (Transmit Packet Steering). Without tuning one 5-tuple will exit over one TX queue. Now, is that ever a performance problem - I doubt, but I guess it can depend on context.

**Comment by gz** [comment]
The problem is not the TX queue on the sender, but the fact that on the receiver NIC all packets end up in the same RX queue since the RX flow hashing is looking at src ip, src port, dest ip, dest port.

**Comment by majek** [comment]
The point of the blog post and this code is to show precisely that- how can you do scaling on RX side.

**Comment by gz** [comment]
Yes but the code, as you have it here is not optimal in that respect (if you use just one udpsender process). All your packages will end up on one queue at the receiving NIC since the src port and ip will look the same for all incoming packages.

You already mention the problem in your post:
"More investigation will reveal further room for improvement. Even though we started four receiving threads, the load is not being spread evenly across them:"

If you had a different source port for each incoming connection, the packets would be distributed evenly.

**Comment by majek** [comment]
Sir. 

Before "Crash course to multi-queue NICs" headline, the blog post speaks about a single 5-tuple hash.

After that headline the blog explains multi-queue nics and shows clearly that doing >one 5 tuple will distribute the load across multuple RX queues.

The "more investigation" comment is specifically about multiple 5-tuples not being load balanced on the RX side by the SO_REUSEPORT. If I read you right, you seem to assume that a single SO_REUSEPORT socket always reads from exactly single RX socket. This is not the case.

Packets get received from RX queue, then *hashed again*, with different algo on SO_REUSEPORT layer, and then pushed to relevant socket. In other words, there is *no relationship* between SO_REUSEPORT sockets and RX queues.

Unless you specifically configure SO_REUSEPORT algo to look at RX CPU number, but this is another story.
